Feature add timber integration
sentry-demos/android pull request #18
Opened 2021-01-15 23:01 UTC by idosun

2021-01-16 00:34 UTC, thinkocapo requested changes
Was capturing native crashes by NDK overall broken, you found? Is that why there’s a lot of updates for NDK?

Can you put a few links to your Sentry Issues (from Timber, and anything with the new CustomerType tag, and definitely the Native Crash from NDK).

2021-01-16 00:34 UTC, thinkocapo commented on Makefile
> +all: gradle_build setup_release upload_debug_files
wasn't this already being taken care of by something else, if I'm not mistaken?

or did you find crashes weren't symbolicated, or you were lacking stack traces?

2021-01-16 00:34 UTC, thinkocapo commented on app/build.gradle
> +        versionCode 15
ok this is not the SDK's version. Is this the Android API version or our App's version? Was this downgrade needed for TImber to work?

2021-01-16 00:34 UTC, thinkocapo commented on app/build.gradle
> +    autoUpload true
if it's `autoUpload true` then does that mean we don't need to use sentry-cli for the `upload_debug_files` defined in the Makefile?

2021-01-16 02:01 UTC, idosun commented on app/build.gradle
> +    autoUpload true
autoUpload -  is for proguard mapping files that are then uploaded to project settings > proguard mapping

2021-01-19 22:57 UTC, closed without merging

2021-01-19 22:58 UTC, idosun commented
will create new PR